version: '3.8'

services:
#    front:
#        build:
#            context: ./front/
#        volumes:
#            - transcendence:/app
#        container_name: front
    db:
        image: postgres:13
        container_name: db
        environment:
            POSTGRES_DB: PGdatabase
            POSTGRES_USER: PGuser
            POSTGRES_PASSWORD: PGpassword
        ports:
            - '5432:5432'
        networks:
            - app-network

    back:
        build:
            context: ./back/
        volumes:
            - transcendence:/backup
        container_name: back 
        ports:
            - '8000:8000'
        environment:
            - POSTGRES_DB=${POSTGRES_DB}
            - POSTGRES_USER=${POSTGRES_USER}
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
        depends_on:
            - db
        networks:
            - app-network
    



volumes:
     transcendence:
        driver: local
        driver_opts:
           type: none
           o: bind
           device: ~/sgoinfre/transcendence

networks:
    app-network:
        driver: bridge