version: '3.8'

services:
    db:
        image: postgres:13
        container_name: db
        env_file:
            - ./back/.env
        ports:
            - '5432:5432'
        networks:
            - app-network

    back:
        build:
            context: ./back/
        container_name: back 
        env_file:
            - ./back/.env
        depends_on:
            - db
        networks:
            - app-network
    

    nginx:
        build:
            context: ./nginx/
        container_name: nginx
        ports:
            - '8000:8000'
            - '8080:8080'
        depends_on:
            - back
        networks:
            - app-network

networks:
    app-network:
        driver: bridge
