version: '3.8'

services:
#    front:
#        build:
#            context: ./front/
#        volumes:
#            - transcendence:/app
#        container_name: front
    back:
        build:
            context: ./back/
        volumes:
            - transcendence:/app
        container_name: back 
        ports:
            - '8000:8000'
volumes:
     transcendence:
        driver: local
        driver_opts:
           type: none
           o: bind
           device: ~/sgoinfre/transcendence
